apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: wpiiyy37l-go-gitops
  description: This is GitOps manifest for wpiiyy37l-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: tssc/gitops=wpiiyy37l-go
    backstage.io/kubernetes-id: wpiiyy37l-go 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: wpiiyy37l-go
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:wpiiyy37l-go
